// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/gempellm/go_chan_api/v1/go_chan_api.proto

package go_chan_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MediaType - Type of attached media
type MediaType int32

const (
	MediaType_TYPE_IMAGE MediaType = 0
	MediaType_TYPE_VIDEO MediaType = 1
)

var MediaType_name = map[int32]string{
	0: "TYPE_IMAGE",
	1: "TYPE_VIDEO",
}

var MediaType_value = map[string]int32{
	"TYPE_IMAGE": 0,
	"TYPE_VIDEO": 1,
}

func (x MediaType) String() string {
	return proto.EnumName(MediaType_name, int32(x))
}

func (MediaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{0}
}

// Post - Basic go-chan unit
type Post struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId             uint64               `protobuf:"varint,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Msg                  string               `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Media                *Media               `protobuf:"bytes,6,opt,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetThreadId() uint64 {
	if m != nil {
		return m.ThreadId
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Post) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Post) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

// Media - Attached media to the post
type Media struct {
	File                 [][]byte    `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	FileType             []MediaType `protobuf:"varint,2,rep,packed,name=file_type,json=fileType,proto3,enum=gempellm.go_chan_api.v1.MediaType" json:"file_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{1}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetFile() [][]byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Media) GetFileType() []MediaType {
	if m != nil {
		return m.FileType
	}
	return nil
}

type DescribePostV1Request struct {
	PostId               uint64   `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribePostV1Request) Reset()         { *m = DescribePostV1Request{} }
func (m *DescribePostV1Request) String() string { return proto.CompactTextString(m) }
func (*DescribePostV1Request) ProtoMessage()    {}
func (*DescribePostV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{2}
}

func (m *DescribePostV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePostV1Request.Unmarshal(m, b)
}
func (m *DescribePostV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePostV1Request.Marshal(b, m, deterministic)
}
func (m *DescribePostV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePostV1Request.Merge(m, src)
}
func (m *DescribePostV1Request) XXX_Size() int {
	return xxx_messageInfo_DescribePostV1Request.Size(m)
}
func (m *DescribePostV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePostV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePostV1Request proto.InternalMessageInfo

func (m *DescribePostV1Request) GetPostId() uint64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type DescribePostV1Response struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribePostV1Response) Reset()         { *m = DescribePostV1Response{} }
func (m *DescribePostV1Response) String() string { return proto.CompactTextString(m) }
func (*DescribePostV1Response) ProtoMessage()    {}
func (*DescribePostV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{3}
}

func (m *DescribePostV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePostV1Response.Unmarshal(m, b)
}
func (m *DescribePostV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePostV1Response.Marshal(b, m, deterministic)
}
func (m *DescribePostV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePostV1Response.Merge(m, src)
}
func (m *DescribePostV1Response) XXX_Size() int {
	return xxx_messageInfo_DescribePostV1Response.Size(m)
}
func (m *DescribePostV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePostV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePostV1Response proto.InternalMessageInfo

func (m *DescribePostV1Response) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type CreatePostV1Request struct {
	ThreadId             uint64   `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Media                *Media   `protobuf:"bytes,4,opt,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostV1Request) Reset()         { *m = CreatePostV1Request{} }
func (m *CreatePostV1Request) String() string { return proto.CompactTextString(m) }
func (*CreatePostV1Request) ProtoMessage()    {}
func (*CreatePostV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{4}
}

func (m *CreatePostV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostV1Request.Unmarshal(m, b)
}
func (m *CreatePostV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostV1Request.Marshal(b, m, deterministic)
}
func (m *CreatePostV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostV1Request.Merge(m, src)
}
func (m *CreatePostV1Request) XXX_Size() int {
	return xxx_messageInfo_CreatePostV1Request.Size(m)
}
func (m *CreatePostV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostV1Request proto.InternalMessageInfo

func (m *CreatePostV1Request) GetThreadId() uint64 {
	if m != nil {
		return m.ThreadId
	}
	return 0
}

func (m *CreatePostV1Request) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostV1Request) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreatePostV1Request) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type CreatePostV1Response struct {
	PostId               uint64   `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostV1Response) Reset()         { *m = CreatePostV1Response{} }
func (m *CreatePostV1Response) String() string { return proto.CompactTextString(m) }
func (*CreatePostV1Response) ProtoMessage()    {}
func (*CreatePostV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{5}
}

func (m *CreatePostV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostV1Response.Unmarshal(m, b)
}
func (m *CreatePostV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostV1Response.Marshal(b, m, deterministic)
}
func (m *CreatePostV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostV1Response.Merge(m, src)
}
func (m *CreatePostV1Response) XXX_Size() int {
	return xxx_messageInfo_CreatePostV1Response.Size(m)
}
func (m *CreatePostV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostV1Response proto.InternalMessageInfo

func (m *CreatePostV1Response) GetPostId() uint64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type ListPostsV1Request struct {
	ThreadId             uint64   `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsV1Request) Reset()         { *m = ListPostsV1Request{} }
func (m *ListPostsV1Request) String() string { return proto.CompactTextString(m) }
func (*ListPostsV1Request) ProtoMessage()    {}
func (*ListPostsV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{6}
}

func (m *ListPostsV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsV1Request.Unmarshal(m, b)
}
func (m *ListPostsV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsV1Request.Marshal(b, m, deterministic)
}
func (m *ListPostsV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsV1Request.Merge(m, src)
}
func (m *ListPostsV1Request) XXX_Size() int {
	return xxx_messageInfo_ListPostsV1Request.Size(m)
}
func (m *ListPostsV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsV1Request proto.InternalMessageInfo

func (m *ListPostsV1Request) GetThreadId() uint64 {
	if m != nil {
		return m.ThreadId
	}
	return 0
}

type ListPostsV1Response struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsV1Response) Reset()         { *m = ListPostsV1Response{} }
func (m *ListPostsV1Response) String() string { return proto.CompactTextString(m) }
func (*ListPostsV1Response) ProtoMessage()    {}
func (*ListPostsV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{7}
}

func (m *ListPostsV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsV1Response.Unmarshal(m, b)
}
func (m *ListPostsV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsV1Response.Marshal(b, m, deterministic)
}
func (m *ListPostsV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsV1Response.Merge(m, src)
}
func (m *ListPostsV1Response) XXX_Size() int {
	return xxx_messageInfo_ListPostsV1Response.Size(m)
}
func (m *ListPostsV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsV1Response proto.InternalMessageInfo

func (m *ListPostsV1Response) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type RemovePostV1Request struct {
	PostId               uint64   `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePostV1Request) Reset()         { *m = RemovePostV1Request{} }
func (m *RemovePostV1Request) String() string { return proto.CompactTextString(m) }
func (*RemovePostV1Request) ProtoMessage()    {}
func (*RemovePostV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{8}
}

func (m *RemovePostV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePostV1Request.Unmarshal(m, b)
}
func (m *RemovePostV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePostV1Request.Marshal(b, m, deterministic)
}
func (m *RemovePostV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePostV1Request.Merge(m, src)
}
func (m *RemovePostV1Request) XXX_Size() int {
	return xxx_messageInfo_RemovePostV1Request.Size(m)
}
func (m *RemovePostV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePostV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePostV1Request proto.InternalMessageInfo

func (m *RemovePostV1Request) GetPostId() uint64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type RemovePostV1Response struct {
	Found                bool     `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePostV1Response) Reset()         { *m = RemovePostV1Response{} }
func (m *RemovePostV1Response) String() string { return proto.CompactTextString(m) }
func (*RemovePostV1Response) ProtoMessage()    {}
func (*RemovePostV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd637e927a7b7d7e, []int{9}
}

func (m *RemovePostV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePostV1Response.Unmarshal(m, b)
}
func (m *RemovePostV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePostV1Response.Marshal(b, m, deterministic)
}
func (m *RemovePostV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePostV1Response.Merge(m, src)
}
func (m *RemovePostV1Response) XXX_Size() int {
	return xxx_messageInfo_RemovePostV1Response.Size(m)
}
func (m *RemovePostV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePostV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePostV1Response proto.InternalMessageInfo

func (m *RemovePostV1Response) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func init() {
	proto.RegisterEnum("gempellm.go_chan_api.v1.MediaType", MediaType_name, MediaType_value)
	proto.RegisterType((*Post)(nil), "gempellm.go_chan_api.v1.Post")
	proto.RegisterType((*Media)(nil), "gempellm.go_chan_api.v1.Media")
	proto.RegisterType((*DescribePostV1Request)(nil), "gempellm.go_chan_api.v1.DescribePostV1Request")
	proto.RegisterType((*DescribePostV1Response)(nil), "gempellm.go_chan_api.v1.DescribePostV1Response")
	proto.RegisterType((*CreatePostV1Request)(nil), "gempellm.go_chan_api.v1.CreatePostV1Request")
	proto.RegisterType((*CreatePostV1Response)(nil), "gempellm.go_chan_api.v1.CreatePostV1Response")
	proto.RegisterType((*ListPostsV1Request)(nil), "gempellm.go_chan_api.v1.ListPostsV1Request")
	proto.RegisterType((*ListPostsV1Response)(nil), "gempellm.go_chan_api.v1.ListPostsV1Response")
	proto.RegisterType((*RemovePostV1Request)(nil), "gempellm.go_chan_api.v1.RemovePostV1Request")
	proto.RegisterType((*RemovePostV1Response)(nil), "gempellm.go_chan_api.v1.RemovePostV1Response")
}

func init() {
	proto.RegisterFile("api/gempellm/go_chan_api/v1/go_chan_api.proto", fileDescriptor_cd637e927a7b7d7e)
}

var fileDescriptor_cd637e927a7b7d7e = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x6f, 0xd2, 0x50,
	0x14, 0x5f, 0x69, 0xbb, 0xc1, 0x61, 0x21, 0xe4, 0x82, 0xae, 0xc1, 0xa8, 0xa4, 0x4f, 0xc4, 0x41,
	0x2b, 0x6c, 0x6f, 0x8b, 0x31, 0x73, 0x23, 0x0b, 0xea, 0xe2, 0x52, 0xc9, 0x12, 0x8d, 0x49, 0x53,
	0xe8, 0xa5, 0x5c, 0x6d, 0xb9, 0x95, 0x7b, 0x21, 0xd9, 0xb7, 0xf0, 0x5b, 0xf9, 0xec, 0x37, 0x32,
	0xf7, 0x16, 0x48, 0xab, 0x14, 0xf1, 0xa9, 0xe7, 0x9c, 0xfe, 0xce, 0x9f, 0xdf, 0xf9, 0x9d, 0x5c,
	0xe8, 0x78, 0x31, 0xb1, 0x03, 0x1c, 0xc5, 0x38, 0x0c, 0x23, 0x3b, 0xa0, 0xee, 0x78, 0xea, 0xcd,
	0x5c, 0x11, 0x5c, 0x76, 0xd3, 0xae, 0x15, 0xcf, 0x29, 0xa7, 0xe8, 0x64, 0x0d, 0xb5, 0xd2, 0xff,
	0x96, 0xdd, 0xc6, 0xf3, 0x80, 0xd2, 0x20, 0xc4, 0xb6, 0x84, 0x8d, 0x16, 0x13, 0x9b, 0x93, 0x08,
	0x33, 0xee, 0x45, 0x71, 0x92, 0x69, 0xfe, 0x54, 0x40, 0xbb, 0xa3, 0x8c, 0xa3, 0x0a, 0x14, 0x88,
	0x6f, 0x28, 0x4d, 0xa5, 0xa5, 0x39, 0x05, 0xe2, 0xa3, 0x27, 0x50, 0xe2, 0xd3, 0x39, 0xf6, 0x7c,
	0x97, 0xf8, 0x46, 0x41, 0x86, 0x8b, 0x49, 0x60, 0xe0, 0xa3, 0x3a, 0xe8, 0x9c, 0xf0, 0x10, 0x1b,
	0x6a, 0x53, 0x69, 0x95, 0x9c, 0xc4, 0x41, 0x55, 0x50, 0x23, 0x16, 0x18, 0x9a, 0x8c, 0x09, 0x13,
	0x9d, 0xc3, 0xd1, 0x78, 0x8e, 0x3d, 0x8e, 0x7d, 0x43, 0x6f, 0x2a, 0xad, 0x72, 0xaf, 0x61, 0x25,
	0x03, 0x59, 0xeb, 0x81, 0xac, 0xe1, 0x7a, 0x20, 0x67, 0x0d, 0x45, 0xe7, 0xa0, 0x47, 0xd8, 0x27,
	0x9e, 0x71, 0x28, 0x73, 0x9e, 0x59, 0x39, 0xec, 0xac, 0x5b, 0x81, 0x72, 0x12, 0xb0, 0xf9, 0x05,
	0x74, 0xe9, 0x23, 0x04, 0xda, 0x84, 0x84, 0xd8, 0x50, 0x9a, 0x6a, 0xeb, 0xd8, 0x91, 0x36, 0x7a,
	0x0d, 0x25, 0xf1, 0x75, 0xf9, 0x43, 0x8c, 0x8d, 0x42, 0x53, 0x6d, 0x55, 0x7a, 0xe6, 0xee, 0xb2,
	0xc3, 0x87, 0x18, 0x3b, 0x45, 0x91, 0x24, 0x2c, 0xf3, 0x25, 0x3c, 0xba, 0xc6, 0x6c, 0x3c, 0x27,
	0x23, 0x2c, 0xd6, 0x75, 0xdf, 0x75, 0xf0, 0xf7, 0x05, 0x66, 0x1c, 0x9d, 0xc0, 0x51, 0x4c, 0x19,
	0x77, 0x37, 0xcb, 0x3b, 0x14, 0xee, 0xc0, 0x37, 0xdf, 0xc1, 0xe3, 0x3f, 0x33, 0x58, 0x4c, 0x67,
	0x0c, 0xa3, 0x2e, 0x68, 0x02, 0x23, 0xf1, 0xe5, 0xde, 0xd3, 0xdc, 0x39, 0x44, 0x9a, 0x23, 0xa1,
	0xe6, 0x0f, 0x05, 0x6a, 0x57, 0x72, 0x3d, 0xd9, 0xee, 0x19, 0x95, 0x94, 0x3c, 0x95, 0x0a, 0x5b,
	0x54, 0x52, 0xd3, 0x2a, 0xad, 0xf6, 0xad, 0xfd, 0xcf, 0xbe, 0x6d, 0xa8, 0x67, 0x27, 0x5a, 0xb1,
	0xcb, 0x5d, 0x48, 0x17, 0xd0, 0x7b, 0xc2, 0xb8, 0x80, 0xb3, 0xfd, 0x18, 0x98, 0x6f, 0xa1, 0x96,
	0x49, 0x59, 0xb5, 0x38, 0x03, 0x5d, 0xd4, 0x64, 0x52, 0xe2, 0x7f, 0x6e, 0x30, 0xc1, 0x9a, 0x16,
	0xd4, 0x1c, 0x1c, 0xd1, 0xe5, 0xbe, 0xfa, 0xb5, 0xa1, 0x9e, 0xc5, 0xaf, 0x9a, 0xd7, 0x41, 0x9f,
	0xd0, 0xc5, 0x2c, 0x81, 0x17, 0x9d, 0xc4, 0x79, 0x71, 0x0a, 0xa5, 0xcd, 0xd9, 0xa0, 0x0a, 0xc0,
	0xf0, 0xd3, 0x5d, 0xdf, 0x1d, 0xdc, 0x5e, 0xde, 0xf4, 0xab, 0x07, 0x1b, 0xff, 0x7e, 0x70, 0xdd,
	0xff, 0x50, 0x55, 0x7a, 0xbf, 0x54, 0xa8, 0xde, 0xd0, 0xab, 0xa9, 0x37, 0xbb, 0x8c, 0xc9, 0x47,
	0x3c, 0x5f, 0x92, 0x31, 0x46, 0x0c, 0x2a, 0xd9, 0x7b, 0x41, 0x56, 0x2e, 0xaf, 0xad, 0xa7, 0xd8,
	0xb0, 0xf7, 0xc6, 0x27, 0x54, 0xcc, 0x03, 0x14, 0xc1, 0x71, 0x5a, 0x44, 0xd4, 0xce, 0x2d, 0xb1,
	0xe5, 0xfa, 0x1a, 0x9d, 0x3d, 0xd1, 0x9b, 0x76, 0x5f, 0xa1, 0x9c, 0xd2, 0x13, 0x9d, 0xe6, 0xe6,
	0xff, 0x7d, 0x28, 0x8d, 0xf6, 0x7e, 0xe0, 0x34, 0xb5, 0xb4, 0x7e, 0x3b, 0xa8, 0x6d, 0x39, 0x8b,
	0x1d, 0xd4, 0xb6, 0x1d, 0x85, 0x79, 0xf0, 0xe6, 0xd5, 0xe7, 0x8b, 0x80, 0xf0, 0xe9, 0x62, 0x64,
	0x8d, 0x69, 0x94, 0x7e, 0xba, 0x43, 0x6f, 0x16, 0x74, 0x44, 0x01, 0x3b, 0xfe, 0x16, 0xa4, 0xdf,
	0xee, 0x8b, 0x94, 0x3d, 0x3a, 0x94, 0x0f, 0xe2, 0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4,
	0xfc, 0x17, 0x0d, 0xf9, 0x05, 0x00, 0x00,
}
