// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/gempellm/go_chan_api/v1/go_chan_api.proto

package go_chan_api

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MediaType - Type of attached media
type MediaType int32

const (
	MediaType_TYPE_IMAGE MediaType = 0
	MediaType_TYPE_VIDEO MediaType = 1
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "TYPE_IMAGE",
		1: "TYPE_VIDEO",
	}
	MediaType_value = map[string]int32{
		"TYPE_IMAGE": 0,
		"TYPE_VIDEO": 1,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{0}
}

// Post - Basic go-chan unit
type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                             // Post id
	ThreadId uint64               `protobuf:"varint,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"` // Thread id, in which post uploaded
	Title    string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                        // Title of post
	Msg      string               `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`                            // Message of post
	Created  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`                    // Timestamp of post
	Media    *Media               `protobuf:"bytes,6,opt,name=media,proto3" json:"media,omitempty"`                        // Media attached to the post
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Post) GetCreated() *timestamp.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Post) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

// Media - Attached media to the post
type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File     [][]byte    `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	FileType []MediaType `protobuf:"varint,2,rep,packed,name=file_type,json=fileType,proto3,enum=gempellm.go_chan_api.v1.MediaType" json:"file_type,omitempty"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{1}
}

func (x *Media) GetFile() [][]byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Media) GetFileType() []MediaType {
	if x != nil {
		return x.FileType
	}
	return nil
}

type DescribePostV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *DescribePostV1Request) Reset() {
	*x = DescribePostV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribePostV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePostV1Request) ProtoMessage() {}

func (x *DescribePostV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePostV1Request.ProtoReflect.Descriptor instead.
func (*DescribePostV1Request) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{2}
}

func (x *DescribePostV1Request) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type DescribePostV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (x *DescribePostV1Response) Reset() {
	*x = DescribePostV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribePostV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePostV1Response) ProtoMessage() {}

func (x *DescribePostV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePostV1Response.ProtoReflect.Descriptor instead.
func (*DescribePostV1Response) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{3}
}

func (x *DescribePostV1Response) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type CreatePostV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadId uint64 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Msg      string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Media    *Media `protobuf:"bytes,4,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *CreatePostV1Request) Reset() {
	*x = CreatePostV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostV1Request) ProtoMessage() {}

func (x *CreatePostV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostV1Request.ProtoReflect.Descriptor instead.
func (*CreatePostV1Request) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostV1Request) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *CreatePostV1Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostV1Request) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreatePostV1Request) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type CreatePostV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *CreatePostV1Response) Reset() {
	*x = CreatePostV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostV1Response) ProtoMessage() {}

func (x *CreatePostV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostV1Response.ProtoReflect.Descriptor instead.
func (*CreatePostV1Response) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePostV1Response) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type ListPostsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreadId uint64 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
}

func (x *ListPostsV1Request) Reset() {
	*x = ListPostsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsV1Request) ProtoMessage() {}

func (x *ListPostsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsV1Request.ProtoReflect.Descriptor instead.
func (*ListPostsV1Request) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListPostsV1Request) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

type ListPostsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
}

func (x *ListPostsV1Response) Reset() {
	*x = ListPostsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPostsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsV1Response) ProtoMessage() {}

func (x *ListPostsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsV1Response.ProtoReflect.Descriptor instead.
func (*ListPostsV1Response) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListPostsV1Response) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type RemovePostV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *RemovePostV1Request) Reset() {
	*x = RemovePostV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePostV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePostV1Request) ProtoMessage() {}

func (x *RemovePostV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePostV1Request.ProtoReflect.Descriptor instead.
func (*RemovePostV1Request) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{8}
}

func (x *RemovePostV1Request) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type RemovePostV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RemovePostV1Response) Reset() {
	*x = RemovePostV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePostV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePostV1Response) ProtoMessage() {}

func (x *RemovePostV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePostV1Response.ProtoReflect.Descriptor instead.
func (*RemovePostV1Response) Descriptor() ([]byte, []int) {
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP(), []int{9}
}

func (x *RemovePostV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_api_gempellm_go_chan_api_v1_go_chan_api_proto protoreflect.FileDescriptor

var file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2f, 0x67,
	0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f,
	0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x04,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x34, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x22, 0x5c, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d,
	0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x30, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x70, 0x6f,
	0x73, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x34, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x22, 0x2f, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x13, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x05,
	0x70, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x2e, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x2a, 0x2b, 0x0a, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x01,
	0x32, 0xae, 0x04, 0x0a, 0x10, 0x47, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x41, 0x70, 0x69, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x89, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x31, 0x12, 0x2e, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65,
	0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56,
	0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65,
	0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x10, 0x12, 0x0e, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x7d, 0x12, 0x7d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56,
	0x31, 0x12, 0x2c, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2d, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x22, 0x05, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x3a, 0x01, 0x2a,
	0x12, 0x85, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x56, 0x31,
	0x12, 0x2b, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63,
	0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x2f, 0x7b, 0x74, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x86, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x31, 0x12, 0x2c, 0x2e, 0x67, 0x65, 0x6d, 0x70,
	0x65, 0x6c, 0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c,
	0x6c, 0x6d, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x2a, 0x11,
	0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2f, 0x7b, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x7d, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x65, 0x6d, 0x70, 0x65, 0x6c, 0x6c, 0x6d, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d,
	0x63, 0x68, 0x61, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x3b, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescOnce sync.Once
	file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescData = file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDesc
)

func file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescGZIP() []byte {
	file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescOnce.Do(func() {
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescData)
	})
	return file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDescData
}

var file_api_gempellm_go_chan_api_v1_go_chan_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_gempellm_go_chan_api_v1_go_chan_api_proto_goTypes = []interface{}{
	(MediaType)(0),                 // 0: gempellm.go_chan_api.v1.MediaType
	(*Post)(nil),                   // 1: gempellm.go_chan_api.v1.Post
	(*Media)(nil),                  // 2: gempellm.go_chan_api.v1.Media
	(*DescribePostV1Request)(nil),  // 3: gempellm.go_chan_api.v1.DescribePostV1Request
	(*DescribePostV1Response)(nil), // 4: gempellm.go_chan_api.v1.DescribePostV1Response
	(*CreatePostV1Request)(nil),    // 5: gempellm.go_chan_api.v1.CreatePostV1Request
	(*CreatePostV1Response)(nil),   // 6: gempellm.go_chan_api.v1.CreatePostV1Response
	(*ListPostsV1Request)(nil),     // 7: gempellm.go_chan_api.v1.ListPostsV1Request
	(*ListPostsV1Response)(nil),    // 8: gempellm.go_chan_api.v1.ListPostsV1Response
	(*RemovePostV1Request)(nil),    // 9: gempellm.go_chan_api.v1.RemovePostV1Request
	(*RemovePostV1Response)(nil),   // 10: gempellm.go_chan_api.v1.RemovePostV1Response
	(*timestamp.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_api_gempellm_go_chan_api_v1_go_chan_api_proto_depIdxs = []int32{
	11, // 0: gempellm.go_chan_api.v1.Post.created:type_name -> google.protobuf.Timestamp
	2,  // 1: gempellm.go_chan_api.v1.Post.media:type_name -> gempellm.go_chan_api.v1.Media
	0,  // 2: gempellm.go_chan_api.v1.Media.file_type:type_name -> gempellm.go_chan_api.v1.MediaType
	1,  // 3: gempellm.go_chan_api.v1.DescribePostV1Response.post:type_name -> gempellm.go_chan_api.v1.Post
	2,  // 4: gempellm.go_chan_api.v1.CreatePostV1Request.media:type_name -> gempellm.go_chan_api.v1.Media
	1,  // 5: gempellm.go_chan_api.v1.ListPostsV1Response.posts:type_name -> gempellm.go_chan_api.v1.Post
	3,  // 6: gempellm.go_chan_api.v1.GoChanApiService.DescribePostV1:input_type -> gempellm.go_chan_api.v1.DescribePostV1Request
	5,  // 7: gempellm.go_chan_api.v1.GoChanApiService.CreatePostV1:input_type -> gempellm.go_chan_api.v1.CreatePostV1Request
	7,  // 8: gempellm.go_chan_api.v1.GoChanApiService.ListPostsV1:input_type -> gempellm.go_chan_api.v1.ListPostsV1Request
	9,  // 9: gempellm.go_chan_api.v1.GoChanApiService.RemovePostV1:input_type -> gempellm.go_chan_api.v1.RemovePostV1Request
	4,  // 10: gempellm.go_chan_api.v1.GoChanApiService.DescribePostV1:output_type -> gempellm.go_chan_api.v1.DescribePostV1Response
	6,  // 11: gempellm.go_chan_api.v1.GoChanApiService.CreatePostV1:output_type -> gempellm.go_chan_api.v1.CreatePostV1Response
	8,  // 12: gempellm.go_chan_api.v1.GoChanApiService.ListPostsV1:output_type -> gempellm.go_chan_api.v1.ListPostsV1Response
	10, // 13: gempellm.go_chan_api.v1.GoChanApiService.RemovePostV1:output_type -> gempellm.go_chan_api.v1.RemovePostV1Response
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_gempellm_go_chan_api_v1_go_chan_api_proto_init() }
func file_api_gempellm_go_chan_api_v1_go_chan_api_proto_init() {
	if File_api_gempellm_go_chan_api_v1_go_chan_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribePostV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribePostV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPostsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePostV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePostV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gempellm_go_chan_api_v1_go_chan_api_proto_goTypes,
		DependencyIndexes: file_api_gempellm_go_chan_api_v1_go_chan_api_proto_depIdxs,
		EnumInfos:         file_api_gempellm_go_chan_api_v1_go_chan_api_proto_enumTypes,
		MessageInfos:      file_api_gempellm_go_chan_api_v1_go_chan_api_proto_msgTypes,
	}.Build()
	File_api_gempellm_go_chan_api_v1_go_chan_api_proto = out.File
	file_api_gempellm_go_chan_api_v1_go_chan_api_proto_rawDesc = nil
	file_api_gempellm_go_chan_api_v1_go_chan_api_proto_goTypes = nil
	file_api_gempellm_go_chan_api_v1_go_chan_api_proto_depIdxs = nil
}
